# Generated by Django 3.1.1 on 2020-10-05 21:25

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('party', models.CharField(max_length=20)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudyCasesManage.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=20)),
                ('created_date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('followers', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('mentions', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudyCasesManage.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_date', models.DateField()),
                ('end_date', models.DateField()),
                ('social_media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyCasesManage.socialmediaaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('post_text', models.CharField(max_length=100)),
                ('post', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='StudyCasesManage.post')),
                ('timeline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyCasesManage.timeline')),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_date', models.DateField()),
                ('release_date', models.DateField()),
                ('provider', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=10)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyCasesManage.candidate')),
            ],
        ),
    ]
