# Generated by Django 3.1.1 on 2020-10-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0005_auto_20201006_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
