# Generated by Django 3.1.1 on 2020-10-08 00:05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0006_auto_20201007_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_as_json',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='followers',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='mentions',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
