# Generated by Django 3.1.1 on 2020-10-08 00:09

import datetime
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0007_auto_20201007_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='StudyCasesManage.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_as_json',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='followers',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='mentions',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='collect_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
