# Generated by Django 3.1.1 on 2020-10-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0008_auto_20201007_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='upload',
            field=models.FileField(default=None, upload_to='uploads/manifests/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
