# Generated by Django 3.1.1 on 2020-10-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0010_auto_20201007_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/manifests/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d'),
        ),
    ]
