# Generated by Django 3.1.1 on 2020-10-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0011_auto_20201007_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='location',
        ),
        migrations.AlterField(
            model_name='manifest',
            name='upload',
            field=models.FileField(upload_to='uploads/manifests/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d'),
        ),
    ]
