# Generated by Django 3.1.1 on 2020-10-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0012_auto_20201007_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='upload',
            field=models.FileField(max_length=400, upload_to='StudyCasesManage/uploads/manifests/%Y/%m/%d'),
        ),
    ]
