# Generated by Django 3.1.1 on 2020-10-15 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0014_auto_20201015_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='campaign_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyCasesManage.campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='StudyCasesManage.post'),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyCasesManage.candidate', verbose_name='Candidate'),
        ),
    ]
