# Generated by Django 3.1.1 on 2020-10-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0016_auto_20201015_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='upload',
            new_name='document',
        ),
        migrations.AlterField(
            model_name='manifest',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
