# Generated by Django 3.1.1 on 2020-10-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0017_auto_20201015_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='candidate_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudyCasesManage.candidate', verbose_name='Candidate'),
        ),
    ]
