# Generated by Django 3.1.1 on 2020-10-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0018_auto_20201016_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='id',
        ),
        migrations.AlterField(
            model_name='manifest',
            name='candidate_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudyCasesManage.candidate', verbose_name='Candidate'),
        ),
    ]
