# Generated by Django 3.1.1 on 2020-10-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0019_auto_20201016_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
