# Generated by Django 3.1.1 on 2020-10-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0022_auto_20201016_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='document',
            new_name='manifest',
        ),
    ]
