# Generated by Django 3.1.1 on 2020-10-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0024_auto_20201016_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
