# Generated by Django 3.1.1 on 2020-10-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0029_auto_20201016_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
