# Generated by Django 3.1.1 on 2020-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0030_auto_20201016_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
