# Generated by Django 3.1.3 on 2020-11-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCasesManage', '0032_auto_20201112_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='manifest',
            field=models.FileField(max_length=400, upload_to='StudyCasesManage/manifests'),
        ),
    ]
